// preset/ai-cad-dsh/web/build.mjs
// 构建 DSH 客户端 bundle：1) 把 occt-import-js.wasm 读成 base64 写进 src/generated/wasm-b64.ts；
// 2) esbuild 打包 src/index.ts 为 CJS bundle，包进 window.__ModuleLoader__.load 工厂。
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)));
export const PKG_ID = '@ai-cad/cad3d-preview';

// 1) wasm → base64 → 生成 TS 常量文件
const wasmPath = resolve(root, 'node_modules/occt-import-js/dist/occt-import-js.wasm');
const b64 = readFileSync(wasmPath).toString('base64');
const generatedDir = resolve(root, 'src/generated');
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  resolve(generatedDir, 'wasm-b64.ts'),
  '// generated by build.mjs — do not edit\nexport const OCCT_WASM_BASE64 = ' +
    JSON.stringify(b64) + ';\n',
);

// 2) esbuild CJS bundle + __ModuleLoader__.load 包装
// banner 打开工厂：定义 module/exports（工厂闭包内），materialize 时返回 module.exports。
// react 等 shell seed 外置（external），bundle 内保持 require('react') 调用。
const banner = `window.__ModuleLoader__.load({ id: ${JSON.stringify(PKG_ID)}, factory: (require) => {\nvar module = { exports: {} };\nvar exports = module.exports;\nObject.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });\n`;
const footer = '\nreturn module.exports;\n} });\n';

// occt-import-js 的 dist 含 Emscripten node 分支（if(ENVIRONMENT_IS_NODE){ require('fs'/'path'/'crypto') }），
// 浏览器运行时该分支不执行。platform:browser 下 esbuild 会静态解析这些 require 并因 node 内建报错，
// 故以空桩满足静态解析（运行时由 ENVIRONMENT_IS_NODE 守卫，空桩永不被调用）。
const nodeBuiltinStub = {
  name: 'node-builtin-stub',
  setup(build) {
    const stub = { namespace: 'node-builtin-stub', path: 'empty' };
    build.onResolve({ filter: /^(fs|path|crypto|node:fs|node:path|node:crypto)$/ }, () => stub);
    build.onLoad({ filter: /.*/, namespace: 'node-builtin-stub' }, () => ({ contents: 'module.exports = {};', loader: 'js' }));
  },
};

await build({
  entryPoints: [resolve(root, 'src/index.ts')],
  outfile: resolve(root, 'dist/client.js'),
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  sourcemap: true,
  jsx: 'automatic',
  external: ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/client'],
  plugins: [nodeBuiltinStub],
  banner: { js: banner },
  footer: { js: footer },
});
